name: sysfoo-demo
on: push
jobs:
  sysfoo-job:
    runs-on: ubuntu-latest
    steps:
     - name: Hello World
       run: echo "Welcome to Training"
     - name: code checkout
       uses: actions/checkout@v6
     - name: test
       run: mvn test
     - name: clean package
       run: mvn clean
     - name: package
       run: mvn package
     - name: view files
       run: ls -ltr target
